var config = {
  texts: [
    "Thanh Miện, 25/1/2023",
    "Vậy là một năm nữa lại trôi qua",
    "trong nháy mắt.",
    "Hôm nay là một ngày đặc biệt, ",
    "đặc biệt như chính cậu vậy.",
    "Ngày mà 23 năm về trước",
    "một thiên thần nhỏ được sinh ra đời.",
    "Tớ làm tất cả những điều này… ",
    "giống như một món quà nhỏ dành tặng cậu.",
    "Cảm ơn cậu vì đã ở đây.",
    "Tớ chúc cho cậu có được...",
    "mọi điều tốt đẹp nhất,",
    "tất cả mong muốn của cậu sẽ thành sự thật.",
    "Hãy sống như một con chim tự do,",
    "bay trên bầu trời xanh.",
    "Cuộc sống có thể không dễ dàng",
    "như ta mong muốn.",
    "Nhưng...",
    "Đừng sợ.",
    "Đừng lo lắng.",
    "Tại vì...",
    "Cậu không đơn độc trên thế giới này.",
    "Cậu thực sự quan trọng",
    "và đặc biệt với nhiều người...",
    "trong đó có tớ.",
    "Cậu xứng đáng được yêu thương.",
    "Hãy tận hưởng cuộc sống này,",
    "hãy lấp đầy nó bằng...",
    "nụ cười đẹp nhất của cậu.",
    "Hmmm...",
    "một cô gái có bàn tay lạnh.",
    "Tớ hi vọng món quà này sẽ ở bên cậu,",
    "đem lại cậu được cảm giác ấm áp,",
    "có thể làm dịu đi những cơn đau",
    "mỗi khi cậu tới tháng.",
    "Hãy giữ nó...",
    "cậu nhé!",
    "Tớ xin lỗi, xin lỗi vì tất cả.",
    "Xin lỗi vì đã không có",
    "màn tỏ tình đặc biệt nào cả.",
    "Tớ thấy cậu đã đủ mệt mỏi với tớ rồi.",
    "Tớ biết",
    "cả tớ và cậu đã cố gắng rất nhiều",
    "nhưng tớ không đủ tốt",
    "không đủ để khiến cậu tin tưởng.",
    "Tớ ghét 2 từ “bỏ cuộc”.",
    "Tớ vẫn nói với cậu...",
    "đừng hỏi tớ tại sao",
    "vì tớ cũng chỉ biết trả lời...",
    "bằng 2 từ “cảm giác”.",
    "Được ở bên cậu,",
    "quan tâm, chăm sóc cho cậu...",
    "nó cũng mang lại cho tớ ",
    "cảm giác hạnh phúc.",
    "Nhưng cũng đến lúc",
    "tớ cảm giác được...",
    "cậu đã rất khó chịu về tớ",
    "cảm giác như cậu",
    "thực sự ghét tớ.",
    "Sự việc ngày hôm qua",
    "có lẽ đã đi quá giới hạn.",
    "Vậy nên",
    "tớ chọn cách tôn trọng cậu",
    "tôn trọng bản thân mình.",
    "Cảm ơn cậu đã đến,",
    "đã cho tớ biết",
    "thế nào là “hạnh phúc” ",
    "thế nào là yêu một người.",
    "Cảm ơn vì...",
    "đã dạy cho tớ nhiều thứ.",
    "Tớ mong rằng",
    "sẽ có một người nào đó",
    "yêu thương cậu hết lòng,",
    "một người cho cậu được",
    "cảm giác an toàn khi ở bên,",
    "một người khiến cậu thực sự tin tưởng.",
    "Yêu cậu <3",
    "...",
    "Chúng ta còn có thể là bạn không?",
  ],

  desc: {
    turn_on: "Bật đèn",
    play: "Phát nhạc",
    bannar_coming: "Trang trí",
    balloons_flying: "Bóng bay",
    cake_fadein: "Chiếc bánh đặc biệt",
    light_candle: "Thắp nến",
    wish_message: "Happy Birthday",
    story: "Một vài lời nhắn",
  },
};
